FROM python:_version_

RUN pip install poetry==1.1.4

WORKDIR /app

COPY pyproject.toml /app
COPY poetry.lock /app
COPY README.md /app

RUN poetry install

ADD gradient_utils /app/gradient_utils
ADD tests /app/tests